FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9
COPY ./pyproject.toml /pyproject.toml
RUN pip install poetry
RUN poetry export -f requirements.txt --output /requirements.txt
RUN pip install -r /requirements.txt
CMD [ "/start-reload.sh" ]
